<?xml version="1.0"?>
<robot name="obstacle" xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <!-- Constants setting for obstacle dimensions -->
    <!-- width and thick of moving plane -->
    <xacro:property name="p_width" value="0.20" />
    <xacro:property name="p_thick" value="0.01" />

    <!-- width and thick of obstacle -->
    <xacro:property name="o_width" value="0.15" />
    <xacro:property name="o_length" value="0.15" />
    <xacro:property name="o_height" value="0.3" />

    <!-- Import your model behavior in Gazebo -->
    <xacro:include filename="$(find od_description)/urdf/obstacle.gazebo.xacro" />
    <!-- Import Rviz colors -->
    <xacro:include filename="$(find od_description)/urdf/materials.xacro" />

    <!-- Define your rrbot model -->
    <xacro:macro name="obstacle" params="name *origin">

    <!-- Propagate the name to all elements to make them unique -->
<!-- * * * Link Definitions * * * -->


<!-- y moving plane -->

    <link name="${name}_x_link">
 	<inertial>
            <origin rpy="0.0 0 0" xyz="0 0 0"/>
            <mass value="1" />
            <inertia ixx="7.58333333333e-07" ixy="0.0" ixz="0.0" iyy="7.58333333333e-07" iyz="0.0" izz="1.25e-06"/>
        </inertial>
    </link>

    <joint name="${name}_x_joint" type="prismatic">
        <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
        <parent link="world" />
        <child link="${name}_x_link" />
        <axis xyz="1 0 0" />
        <limit effort="10000" lower="-15" upper="15.0" velocity="100" />
        <!--<dynamics damping="100.0" />-->
    </joint>


<!-- y moving plane -->

    <link name="${name}_y_link">
 	    <inertial>
            <origin rpy="0.0 0 0" xyz="0 0 0"/>
            <mass value="1" />
            <inertia ixx="7.58333333333e-07" ixy="0.0" ixz="0.0" iyy="7.58333333333e-07" iyz="0.0" izz="1.25e-06"/>
        </inertial>
    </link>

    <joint name="${name}_y_joint" type="prismatic">
        <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
        <parent link="${name}_x_link" />
        <child link="${name}_y_link" />
        <axis xyz="0 1 0" />
        <limit effort="10000" lower="-15.0" upper="15.0" velocity="100" />
        <!--<dynamics damping="100.0" />-->
    </joint>


<!-- the obstacle -->

    <link name="${name}_entity_link">
 	<inertial>
            <origin rpy="0.0 0 0" xyz="0 0 0"/>
            <mass value="1" />
            <inertia ixx="4.16666666667e-05" ixy="0.0" ixz="0.0" iyy="4.16666666667e-05" iyz="0.0" izz="4.16666666667e-05"/>
        </inertial>
        <collision>
            <origin rpy="0.0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${o_width} ${o_length} ${o_height}"/>
            </geometry>
        </collision>
        <visual>
            <origin rpy="0.0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${o_width} ${o_length} ${o_height}"/>
            </geometry>
        </visual>
    </link>

    <joint name="${name}_entity_link_joint" type="fixed">
        <parent link="${name}_y_link"/>
        <child link="${name}_entity_link"/>
        <origin xyz="0 0 ${o_height/2}" rpy="0 0 0"/>
    </joint>

    <!-- Instance your model behavior in Gazebo keeping the name -->
    <xacro:obstacle_gazebo name="${name}"/>

    </xacro:macro>

</robot>

